name: Deploy Astro Site
on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: pnpm/action-setup@v4  # ¡Agrega la versión aquí!
        with:
          version: 8

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm  # Habilita caching para pnpm

      - uses: withastro/action@v3
        with:
          project: ./
          package-manager: pnpm  # Opcional (ya se usa por defecto)
      
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          enable_jekyll: false